/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatSearchResponse } from '../../models/chat-search-response';

export interface SearchChat$Params {
  query: string;
  page?: number;
  size?: number;
  sort?: string;
  direction?: string;
}

export function searchChat(http: HttpClient, rootUrl: string, params: SearchChat$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatSearchResponse>> {
  const rb = new RequestBuilder(rootUrl, searchChat.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatSearchResponse>;
    })
  );
}

searchChat.PATH = '/api/v1/search/chatbot';
