/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TableDto } from '../../models/table-dto';

export interface CreateTable$Params {
  databaseId: string;
      body: TableDto
}

export function createTable(http: HttpClient, rootUrl: string, params: CreateTable$Params, context?: HttpContext): Observable<StrictHttpResponse<TableDto>> {
  const rb = new RequestBuilder(rootUrl, createTable.PATH, 'post');
  if (params) {
    rb.path('databaseId', params.databaseId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TableDto>;
    })
  );
}

createTable.PATH = '/api/v1/schemas/databases/{databaseId}/tables';
