/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteColumn$Params {
  databaseId: string;
  tableId: string;
  columnId: string;
}

export function deleteColumn(http: HttpClient, rootUrl: string, params: DeleteColumn$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteColumn.PATH, 'delete');
  if (params) {
    rb.path('databaseId', params.databaseId, {});
    rb.path('tableId', params.tableId, {});
    rb.path('columnId', params.columnId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteColumn.PATH = '/api/v1/schemas/databases/{databaseId}/tables/{tableId}/columns/{columnId}';
