/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColumnDto } from '../../models/column-dto';

export interface UpdateColumn$Params {
  databaseId: string;
  tableId: string;
  columnId: string;
      body: ColumnDto
}

export function updateColumn(http: HttpClient, rootUrl: string, params: UpdateColumn$Params, context?: HttpContext): Observable<StrictHttpResponse<ColumnDto>> {
  const rb = new RequestBuilder(rootUrl, updateColumn.PATH, 'patch');
  if (params) {
    rb.path('databaseId', params.databaseId, {});
    rb.path('tableId', params.tableId, {});
    rb.path('columnId', params.columnId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ColumnDto>;
    })
  );
}

updateColumn.PATH = '/api/v1/schemas/databases/{databaseId}/tables/{tableId}/columns/{columnId}';
