/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatDto } from '../models/chat-dto';
import { MessageDto } from '../models/message-dto';
export interface ChatSearchResponse {
  chats?: Array<ChatDto>;
  messages?: Array<MessageDto>;
}
