/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ColumnDto {
  columnId?: string;
  createdAt?: string;
  dataType: string;
  databaseId?: string;
  name: string;
  primaryKey?: boolean;
  tableId?: string;
  foreignTable?: string;
  foreignColumn?: string;
}
