/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageDto {
  confidence?: number;
  content: string;
  createdAt?: string;
  databaseId?: string;
  feedback?: 'GOOD' | 'BAD' | 'NONE';
  messageId?: string;
  senderType?: 'LLM' | 'USER';
}
