/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { TableDto } from '../models/table-dto';
export interface PagedModelTableDto {
  content?: Array<TableDto>;
  page?: PageMetadata;
}
