/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageDto } from '../models/message-dto';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelMessageDto {
  content?: Array<MessageDto>;
  page?: PageMetadata;
}
