/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColumnDto } from '../models/column-dto';
import { DatabaseDto } from '../models/database-dto';
import { TableDto } from '../models/table-dto';
export interface SchemaSearchResponse {
  columns?: Array<ColumnDto>;
  databases?: Array<DatabaseDto>;
  tables?: Array<TableDto>;
}
