/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SchemaImportRequest {
  description?: string;
  isTemplate?: boolean;
  jsonContent: Array<{
[key: string]: any;
}>;
  name: string;
}
