/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TableDto {
  createdAt?: string;
  databaseId?: string;
  description?: string;
  name: string;
  tableId?: string;
}
