/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ExportChatToMarkdown$Params {
  chatID: string;
}

export function exportChatToMarkdown(http: HttpClient, rootUrl: string, params: ExportChatToMarkdown$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, exportChatToMarkdown.PATH, 'get');
  if (params) {
    rb.path('chatID', params.chatID, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

exportChatToMarkdown.PATH = '/api/v1/chatbot/chats/{chatID}/export/markdown';
