/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedModelChatDto } from '../../models/paged-model-chat-dto';

export interface GetChats$Params {
  page?: number;
  size?: number;
  sort?: string;
  direction?: string;
}

export function getChats(http: HttpClient, rootUrl: string, params?: GetChats$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelChatDto>> {
  const rb = new RequestBuilder(rootUrl, getChats.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedModelChatDto>;
    })
  );
}

getChats.PATH = '/api/v1/chatbot/chats';
