/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FeedbackRequest } from '../../models/feedback-request';
import { MessageDto } from '../../models/message-dto';

export interface UpdateMessageFeedback$Params {
  chatID: string;
  messageID: string;
      body: FeedbackRequest
}

export function updateMessageFeedback(http: HttpClient, rootUrl: string, params: UpdateMessageFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageDto>> {
  const rb = new RequestBuilder(rootUrl, updateMessageFeedback.PATH, 'patch');
  if (params) {
    rb.path('chatID', params.chatID, {});
    rb.path('messageID', params.messageID, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageDto>;
    })
  );
}

updateMessageFeedback.PATH = '/api/v1/chatbot/chats/{chatID}/messages/{messageID}/feedback';
