/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChatDto } from '../../models/chat-dto';

export interface UpdateChat$Params {
  chatID: string;
      body: ChatDto
}

export function updateChat(http: HttpClient, rootUrl: string, params: UpdateChat$Params, context?: HttpContext): Observable<StrictHttpResponse<ChatDto>> {
  const rb = new RequestBuilder(rootUrl, updateChat.PATH, 'patch');
  if (params) {
    rb.path('chatID', params.chatID, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChatDto>;
    })
  );
}

updateChat.PATH = '/api/v1/chatbot/chats/{chatID}';
