/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedModelMessageDto } from '../../models/paged-model-message-dto';

export interface GetMessages$Params {
  chatID: string;
  page?: number;
  size?: number;
}

export function getMessages(http: HttpClient, rootUrl: string, params: GetMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelMessageDto>> {
  const rb = new RequestBuilder(rootUrl, getMessages.PATH, 'get');
  if (params) {
    rb.path('chatID', params.chatID, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedModelMessageDto>;
    })
  );
}

getMessages.PATH = '/api/v1/chatbot/chats/{chatID}/messages';
