/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageDto } from '../../models/message-dto';

export interface UpdateMessageContent$Params {
  chatID: string;
  messageID: string;
      body: MessageDto
}

export function updateMessageContent(http: HttpClient, rootUrl: string, params: UpdateMessageContent$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageDto>> {
  const rb = new RequestBuilder(rootUrl, updateMessageContent.PATH, 'patch');
  if (params) {
    rb.path('chatID', params.chatID, {});
    rb.path('messageID', params.messageID, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageDto>;
    })
  );
}

updateMessageContent.PATH = '/api/v1/chatbot/chats/{chatID}/messages/{messageID}';
