/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DatabaseDto } from '../models/database-dto';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelDatabaseDto {
  content?: Array<DatabaseDto>;
  page?: PageMetadata;
}
