/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColumnDto } from '../models/column-dto';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelColumnDto {
  content?: Array<ColumnDto>;
  page?: PageMetadata;
}
