/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChatDto } from '../models/chat-dto';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelChatDto {
  content?: Array<ChatDto>;
  page?: PageMetadata;
}
