/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColumnDto } from '../../models/column-dto';

export interface GetColumns$Params {
  databaseId: string;
  tableId: string;
}

export function getColumns(http: HttpClient, rootUrl: string, params: GetColumns$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ColumnDto>>> {
  const rb = new RequestBuilder(rootUrl, getColumns.PATH, 'get');
  if (params) {
    rb.path('databaseId', params.databaseId, {});
    rb.path('tableId', params.tableId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ColumnDto>>;
    })
  );
}

getColumns.PATH = '/api/v1/schemas/databases/{databaseId}/tables/{tableId}/columns';
