/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TableDto } from '../../models/table-dto';

export interface GetTables$Params {
  databaseId: string;
}

export function getTables(http: HttpClient, rootUrl: string, params: GetTables$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TableDto>>> {
  const rb = new RequestBuilder(rootUrl, getTables.PATH, 'get');
  if (params) {
    rb.path('databaseId', params.databaseId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TableDto>>;
    })
  );
}

getTables.PATH = '/api/v1/schemas/databases/{databaseId}/tables';
