/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DatabaseDto } from '../../models/database-dto';
import { SchemaImportRequest } from '../../models/schema-import-request';

export interface ImportSchema$Params {
      body: SchemaImportRequest
}

export function importSchema(http: HttpClient, rootUrl: string, params: ImportSchema$Params, context?: HttpContext): Observable<StrictHttpResponse<DatabaseDto>> {
  const rb = new RequestBuilder(rootUrl, importSchema.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DatabaseDto>;
    })
  );
}

importSchema.PATH = '/api/v1/schemas/import';
