/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DatabaseDto } from '../../models/database-dto';

export interface UpdateDatabase$Params {
  databaseId: string;
      body: DatabaseDto
}

export function updateDatabase(http: HttpClient, rootUrl: string, params: UpdateDatabase$Params, context?: HttpContext): Observable<StrictHttpResponse<DatabaseDto>> {
  const rb = new RequestBuilder(rootUrl, updateDatabase.PATH, 'patch');
  if (params) {
    rb.path('databaseId', params.databaseId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DatabaseDto>;
    })
  );
}

updateDatabase.PATH = '/api/v1/schemas/databases/{databaseId}';
